"""empty message

Revision ID: a685680bc7e1
Revises: 
Create Date: 2020-03-23 14:42:14.460454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a685680bc7e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('birthdate', sa.String(length=128), nullable=True),
    sa.Column('dogs_cats', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_timestamp'), 'tweet', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_timestamp'), table_name='tweet')
    op.drop_table('tweet')
    op.drop_table('user')
    # ### end Alembic commands ###
